server:
  port: 8080
  error:
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: 'jdbc:sqlserver://soungeserver.database.windows.net;databaseName=sounge'
    username: 'sounge'
    password: '3ads@grupo5'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      globally_quoted_identifiers: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

open-cage:
  api-key: f71f69803a90499d86766b5e246b5072